### ISSUE TITLE
xml.etree.ElementTree.ParseError: mismatched tag: line 23, column 8

### ISSUE THREAD

**Issue by shmick** [michaeldavie/env_canada#14]
I'm getting this error after installing either v0.0.25 or v0.0.27

```
Python 3.7.4 (default, Oct 14 2019, 11:42:47) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from env_canada import ECData
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/env_canada/__init__.py", line 2, in <module>
    from .ec_radar import *
  File "/usr/local/lib/python3.7/site-packages/env_canada/ec_radar.py", line 20, in <module>
    root = et.fromstring(xml_string)
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 23, column 8
```

This is also related to https://github.com/home-assistant/home-assistant/issues/28335

**Comment by michaeldavie** [comment]
Fixed by b02ce139de4f2e2ff15588c853646271142f1282
