### ISSUE TITLE
Respond to errors with defined exceptions

### ISSUE THREAD

**Issue by gwww** [michaeldavie/env_canada#42]
If I do something such as:
```
x=ECWeather(station_id="ON/s1234")
asyncio.run(x.update())
```
I get an exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/glenn/.local/share/asdf/installs/python/3.9.7/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/glenn/.local/share/asdf/installs/python/3.9.7/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/glenn/Development/automation/environment-canada/env_canada/env_canada/ec_weather.py", line 255, in update
    breakpoint()
  File "/Users/glenn/.local/share/asdf/installs/python/3.9.7/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 49
```

The content that was returned is a 404.

All makes sense but would be good  to respond with an exception that is more meaningful when giving errors.

Requesting this so that when the HA config_flow is written there can be meaning errors.

FYI, a pattern to define exceptions that you could follow is here: https://github.com/home-assistant-libs/aioshelly/blob/main/aioshelly/__init__.py#L84-L97

**Comment by michaeldavie** [comment]
That makes sense. The HA component does validate that the site code is in the correct format (using a regex), but it could still not exist.

**Comment by michaeldavie** [comment]
I haven't defined internal exceptions yet, but in v0.5.2 I've made a couple tweaks:
- I've added parameter validation with `voluptuous`, so invalid parameters will be rejected up front with reasonably useful error messages
- Remaining HTTP errors (more likely to be due to server errors) will now be raised from `aiohttp`

https://github.com/michaeldavie/env_canada/compare/v0.5.1...v0.5.2
