### ISSUE TITLE
Unssuported String : "calme"

### ISSUE THREAD

**Issue by v0ltage120** [michaeldavie/env_canada#77]
Hello minor change required I think

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/environment_canada/__init__.py", line 117, in _async_update_data
    await self.ec_data.update()
  File "/usr/local/lib/python3.10/site-packages/env_canada/ec_weather.py", line 423, in update
    self.conditions[c].update(get_condition(meta))
  File "/usr/local/lib/python3.10/site-packages/env_canada/ec_weather.py", line 403, in get_condition
    condition["value"] = int(float(element.text))
ValueError: could not convert string to float: 'calme'

**Comment by michaeldavie** [comment]
Already fixed in #https://github.com/michaeldavie/env_canada/commit/b00303a199c93274707f489ee0e13bccf330bef2

Merged in Home Assistant 2023.4.3.
