### ISSUE TITLE
Jupyter Notebook Error

### ISSUE THREAD

**Issue by JayEmAhch** [michaeldavie/env_canada#79]
Hey Michael. Just wanted to bring something to your attention.  When I tried to run one of the sample codes from the documentation, specifically this one:

import asyncio
from env_canada import ECWeather
ec_en = ECWeather(coordinates=(50, -100))
ec_fr = ECWeather(station_id='ON/s0000430', language='french')
asyncio.run(ec_en.update())
ec_en.conditions
ec_en.daily_forecasts
ec_en.hourly_forecasts
ec_en.alerts

I ran into the following error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[1], line 8
      5 ec_en = ECWeather(coordinates=(50, -100))
      6 ec_fr = ECWeather(station_id='ON/s0000430', language='french')
----> 8 asyncio.run(ec_en.update())
     10 # current conditions
     11 ec_en.conditions

File ~\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py:33, in run(main, debug)
      9 """Execute the coroutine and return the result.
     10 
     11 This function runs the passed coroutine, taking care of
   (...)
     30     asyncio.run(main())
     31 """
     32 if events._get_running_loop() is not None:
---> 33     raise RuntimeError(
     34         "asyncio.run() cannot be called from a running event loop")
     36 if not coroutines.iscoroutine(main):
     37     raise ValueError("a coroutine was expected, got {!r}".format(main))

RuntimeError: asyncio.run() cannot be called from a running event loop

---------------------------------------------------------------------------
I was running this in Jupyter Notebooks when I got the error, but when I ran the same code in PyCharm it worked perfectly. It may be worth putting a note in the documentation that this error can occur when using Jupyter if the code is executed without some modification.

**Comment by smitesht** [comment]
Hello,

I am  also trying to run given example code and getting the same error in both PyCharm and JypiterNotebook.

import asyncio
from env_canada import ECWeather

def print_hi(name):
    # Use a breakpoint in the code line below to debug your script.


    ec_en = ECWeather(coordinates=(50, -100))
    ec_fr = ECWeather(station_id='ON/s0000430', language='french')

    asyncio.run(ec_en.update())

    # current conditions
    ec_en.conditions

    # daily forecasts
    ec_en.daily_forecasts

    # hourly forecasts
    ec_en.hourly_forecasts

    # alerts
    ec_en.alerts


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    print_hi('PyCharm')

**Error:**

Traceback (most recent call last):
  File "C:\Users\tamboli1160\PycharmProjects\pythonProject1\venv\Lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\sslproto.py", line 574, in _on_handshake_complete
    raise handshake_exc
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\sslproto.py", line 556, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\tamboli1160\PycharmProjects\pythonProject1\main.py", line 33, in <module>
    print_hi('PyCharm')
  File "C:\Users\tamboli1160\PycharmProjects\pythonProject1\main.py", line 16, in print_hi
    asyncio.run(ec_en.update())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\tamboli1160\PycharmProjects\pythonProject1\venv\Lib\site-packages\env_canada\ec_weather.py", line 331, in update
    self.site_list = await get_ec_sites()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tamboli1160\PycharmProjects\pythonProject1\venv\Lib\site-packages\env_canada\ec_weather.py", line 246, in get_ec_sites
    response = await session.get(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\tamboli1160\PycharmProjects\pythonProject1\venv\Lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tamboli1160\PycharmProjects\pythonProject1\venv\Lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tamboli1160\PycharmProjects\pythonProject1\venv\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tamboli1160\PycharmProjects\pythonProject1\venv\Lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\tamboli1160\PycharmProjects\pythonProject1\venv\Lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tamboli1160\PycharmProjects\pythonProject1\venv\Lib\site-packages\aiohttp\connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host dd.weather.gc.ca:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')]

Process finished with exit code 1

**Comment by cparmet** [comment]
FWIW, using this `await` approached worked for me in a Jupyter notebook

https://stackoverflow.com/a/55409674

**Comment by michaeldavie** [comment]
I've added a note to the README file to let users know that `await` should be used instead `asyncio.run()` within Jupyter notebooks.
